---
- hosts: all
  vars:
    gem_bin_path: ~/.rvm/gems/$ruby/bin
    locale: en_US.UTF-8
    timezone: America/New_York

  tasks:
    - name: update sudoers
      action: copy src=templates/sudoers dest=/etc/sudoers
      sudo: True

    - name: update apt
      action: command /usr/bin/apt-get update
      sudo: True

    - name: update cache 
      apt: update_cache=yes
      sudo: True

    - name: Generate locales
      command: locale-gen {{ locale }}
      tags: [locale]
      sudo: True

    - name: Set locale
      command: /usr/sbin/update-locale LANG={{ locale }} LC_ALL=$locale
      tags: [locale]
      sudo: True

    # - name: Set /etc/localtime
    #   file: src=/usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime state=link
    #   tags: [locale]
    #   sudo: True

    # - name: set /etc/timezone
    #   template: src=templates/etc/timezone dest=/etc/timezone
    #   notify: update tzdata
    #   tags: [locale]
    #   sudo: True

    - name: install userspace packages
      apt: pkg=$item state=installed
      sudo: True
      with_items:
        - augeas-tools
        - autoconf
        - automake
        - bison
        - build-essential
        - curl
        - emacs
        - git
        - git-core
        - imagemagick
        - libxml2-dev # Nokogiri
        - libxslt1-dev # Nokogiri
        - libyaml-dev
        - libaugeas-dev
        - libaugeas-ruby
        - libc6-dev
        - libcurl4-openssl-dev
        - libffi-dev
        - libgdbm-dev
        - libmagickwand-dev
        - libncurses5-dev
        - libpcre3-dev
        - libpq-dev
        - libreadline6
        - libreadline6-dev
        - libsqlite3-dev 
        - libssl-dev
        - libyaml-dev
        - libxml2-dev 
        - libxslt1-dev
        - libtool
        - memcached
        - openssl
        - pkg-config
        - postgresql
        - postgresql-contrib
        - python-dev
        - python-setuptools
        - python-software-properties
        - python-psycopg2
        - sqlite3
        - tmux
        - vim
        - whois
        - xorg
        - zlib1g 
        - zlib1g-dev 


    - name: install RVM
      shell: curl -L https://get.rvm.io | bash
      tags: [ruby]
      sudo: False

    - name: source the rvm files
      shell: /bin/bash -c 'source /home/vagrant/.rvm/scripts/rvm'
      tags: [ruby]
      sudo: False

    # NEW POSTGRES CONF STUFF

    - name: install python libraries
      action: easy_install name=psycopg2==2.4.5
      sudo: True

    - name: add postgres user to admin/sudo group
      action: user name=postgres groups=sudo append=yes
      sudo: True

    - name: update postgres db configuration
      action: copy src=templates/postgresql.conf dest=/etc/postgresql/9.1/main/postgresql.conf
      sudo: True
      notify:
        - restart postgresql

    - name: update postgres client configuration
      template: src=templates/pg_hba.conf.j2 dest=/etc/postgresql/9.1/main/pg_hba.conf
      sudo: True
      notify:
        - restart postgresql

    - name: ensure database is created
      postgresql_db: name={{dbname}}
      sudo: yes
      sudo_user: postgres

    - name: ensure user has access to database
      postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL
      sudo: yes
      sudo_user: postgres

    # - name: ensure user does not have unnecessary privilege
    #   postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
    #   sudo: yes
    #   sudo_user: postgres
      # END NEW POSTGRES CONF STUFF

    - name: install Ruby 
      shell: /home/vagrant/.rvm/bin/rvm install --default {{ ruby }} # creates=~/.rvm/rubies/$ruby
      sudo: False
      tags: [ruby]

    - name: install base global gems
      shell: /home/vagrant/.rvm/bin/rvm @global do gem install --no-ri --no-rdoc bundler pry pry-doc 
      sudo: False

  handlers:
    - name: restart postgresql
      action: service name=postgresql state=restarted
      sudo: True

    - name: update tzdata
      command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata